### ISSUE TITLE
Refactor the config for more extensibility and separation of concerns

### ISSUE THREAD

**Issue by DavidNix** [strangelove-ventures/sl-exporter#9]
The below is by no means set in stone. A proposal only. 

```yaml
  # Metric name
#  cosmos_asset_exponent:
#    description: "Exponent value for a Cosmos asset"
#    # Metric labels
#    labels: [ "chain", "denom" ]
#    # Static samples
static:
# Are these gauges or counters?
  - { labels: [ "agoric-emerynet-5", "ubld" ], value: 6 }
  - { labels: [ "axelar-dojo-1", "uaxl" ], value: 6 }
  - { labels: [ "cosmoshub-4", "uatom" ], value: 6 }
  - { labels: [ "crescent-1", "ucre" ], value: 6 }
  - { labels: [ "injective-1", "inj" ], value: 18 }
  - { labels: [ "juno-1", "ujuno" ], value: 6 }
  - { labels: [ "osmosis-1", "uosmo" ], value: 6 }
  - { labels: [ "sommelier-3", "usomm" ], value: 6 }
  - { labels: [ "theta-testnet-001", "uatom" ], value: 6 }

cosmos: # cosmos chains only
  - name: agoric-emerynet-5
    rpcs: # probably required
      - https://agoric-rpc.easy2stake.com
      - https://agoric-rpc.polkachu.com
    lcds:
      - https://agoric-lcd.easy2stake.com
      - https://agoric-lcd.polkachu.com
    # User LCD/REST endpoints?
    validators: # optional
        - name: arbitrary name # Or we can use moniker? (I don't think so because it's always "strangelove-ventures")
          consensus_address: abc123
    denom: true

    # Relayer already exports this.
    # But we need this for some validators with orchestrators and side processes.
    # Need to monitor Eth balance as well.
    balances:
      - address: abc123
  # What can we port from cosmos-exporter?

# Use coingecko API
exchange_rates:
# Gauge
  - token: ATOM
#    to: USD # optional or pass for MVP

# Necessary for validator orchestrators like onomy, evmos, and injective
ethereum:
  rpcs:
  - address.infura.com
  balances:
  - wallet
```
